version: 1.0.{build}
before_build:
- ps: nuget restore ./WhenItsDone/WhenItsDone.sln
build:
  project: ./WhenItsDone/WhenItsDone.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - todorov.h@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true